name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
    - name: Run check
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-features -- --include-ignored
